trigger: none

pool: 
  name: linuxAgent

stages:
  - stage: terraform_destroy
    jobs: 
      - job: terraform_destroy
        steps:
          - task: CmdLine@2
            inputs:
              script: |
                az login --identity

          - task: TerraformInstaller@0
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTaskV3@3
            displayName: Terraform Apply
            inputs:
              provider: 'azurerm'
              command: 'destroy'
              commandOptions: '-auto-approve'
              workingDirectory: $(workingDirectory)
              environmentServiceNameAzureRM: $(serviceConnection)
            env:
              TF_VAR_resource_group_root_name: $(resource_group_root_name)
              TF_VAR_resource_group_name: $(resource_group_name)   
              TF_VAR_container_registry_name: $(container_registry_name)
              TF_VAR_source_image_name: $(source_image_name)   
              TF_VAR_ssh_public_key_name: $(ssh_public_key_name)    
              TF_VAR_allowed_ips: $(allowed_ips)
  

