trigger: none

pool:
  name: linuxAgent

stages: 
    - stage: setup_packer_and_identity_for_packer
      jobs:
          - job: install_packer
            steps:
                - task: CmdLine@2
                  displayName: Install
                  inputs:
                      script: |
                        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
                        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
                        sudo apt-get update && sudo apt-get install packer
          - job: authentication_packer
            steps:
                - task: CmdLine@2
                  displayName: Authenticate
                  inputs:
                      script: |
                        az login --identity

    - stage: validate_for_packer
      dependsOn: [setup_packer_and_identity_for_packer]
      condition: succeeded('setup_packer_and_identity_for_packer')
      jobs:
          - job: validate_for_packer
            steps:
                - task: CmdLine@2
                  displayName: Validate
                  inputs:
                      workingDirectory: "packer/"
                      script: |
                        packer init linux-docker.pkr.hcl
                        packer validate linux-docker.pkr.hcl
                  env:
                    PKR_VAR_render_image_name: $(render_image_name)
                    PKR_VAR_resource_group_name: $(resource_group_name)
                    PKR_VAR_build_resource_group_name: $(build_resource_group_name)
    
    - stage: build_for_packer
      dependsOn: [validate_for_packer]
      condition: succeeded('validate_for_packer')
      jobs:
        -  job: build_for_packer
           steps:
                - task: CmdLine@2
                  displayName: Build
                  inputs:
                      workingDirectory: "packer/"
                      script: |
                        packer build -force linux-docker.pkr.hcl
                  env:
                    PKR_VAR_render_image_name: $(render_image_name)
                    PKR_VAR_resource_group_name: $(resource_group_name)
                    PKR_VAR_build_resource_group_name: $(build_resource_group_name)