trigger: none

pool: 
  name: linuxAgent

stages:
  - stage: Packer
    jobs: 
      - job: Authentication
        steps:
          - task: CmdLine@2
            displayName: Authentication
            inputs:
              workingDirectory: 'packer/'
              script: |
                az login --identity

      - job: Validate
        steps:
          - task: CmdLine@2
            displayName: Packer_Install
            inputs:
              workingDirectory: 'packer/'
              script: |
                curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
                sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
                sudo apt-get update && sudo apt-get install packer

          - task: CmdLine@2
            displayName: Packer_Validate
            inputs:
              workingDirectory: 'packer/'
              script: |
                export render_image_name= $render_image_name
                packer init linux-docker.pkr.hcl
                packer validate linux-docker.pkr.hcl
                
          - task: CmdLine@2
            condition: succeeded('Packer Validate')
            displayName: Packer_Build
            inputs:
              workingDirectory: 'packer/'
              script: |
                export render_image_name= $render_image_name
                packer build linux-docker.pkr.hcl
