trigger: none

pool: 
  name: linuxAgent

stages:
  - stage: Build_Image
    jobs: 
      - job: build
        steps:
          - task: CmdLine@2
            inputs:
              script: |
                az login --identity

          - task: PackerBuild@1
            inputs:
              templateType: 'custom'
              customTemplateLocation: 'packer/linux-docker.json'
              customTemplateParameters: '{ "managed_image_resource_group_name": "DevOpsIntern" , "client_id": "feca0420-9d9a-4005-9355-2cb0ec6bc666", "subscription_id": "feca0420-9d9a-4005-9355-2cb0ec6bc666"
              }'

