trigger: none

pr:
  branches:
    include:
      - "feature/*"
      - "develop"

pool:
  name: linuxAgent

variables:
  commit: $(Build.SourceVersion)
  branchname: $(Build.SourceBranchName) 

stages:
  - stage: eslint
    displayName: Test Source Code
    jobs:
      - job: npm_install
        displayName: Install Package
        steps:
        - bash: |
            cd src/ || exit
            npm install
      - job: test
        displayName: Test Source
        dependsOn: ['npm_install']
        condition: succeeded('npm_install')
        steps:
        - bash: |
            cd src/ || exit
            npm run lint
  - stage: docker
    dependsOn: ['eslint']
    condition: succeeded('eslint')
    displayName: Docker Build
    jobs:
      - job: install_docker
        displayName: Install Docker
        steps:
          - bash: |
              sudo apt install docker-compose -y
              docker --version
      - job: build_image
        displayName: Build Docker Image
        dependsOn: ['install_docker']
        condition: succeeded('install_docker')
        steps:
          - bash: |
              cp -r src $(workingDirectory) || exit
              cd $(workingDirectory) || exit
              sudo docker build -t $(urlRegistry)/$(appName)/$(branchname):$(commit) -f Dockerfile.web .
              sudo docker image list