trigger: none

pr:
  branches:
    include:
      - "feature/*"
      - "develop"

pool:
  name: linuxAgent

variables:
  GIT_COMMIT: $(Build.SourceVersion)
  GIT_BRANCH: $(Build.SourceBranch) 

stages:
  - stage: install_docker
    jobs:
      - job: install_docker
        steps:
          - bash: |
              sudo apt install docker-compose -y
              docker --version
      - job: build_image
        dependsOn: ['install_docker']
        condition: succeeded('install_docker')
        steps:
          - bash: |
              branchName="$(echo $GIT_BRANCH | cut -d '/' -f 3-)"
              cp -r src $(workingDirectory) || exit
              cd $(workingDirectory) || exit
              sudo docker build -t $(urlRegistry)/$(appName)/$branchName:$GIT_COMMIT -f Dockerfile.web .
              sudo docker image list