pr:
  - feature/*

pool:
  name: linuxAgent

variables:
  GIT_COMMIT: $(Build.SourceVersion)
  GIT_BRANCH: $(Build.SourceBranch) 

stages:
  - stage: install_docker
    jobs:
      - job: install_docker
        steps:
          - task: DockerInstaller@0
            inputs:
              dockerVersion: '17.09.0-ce'
              releaseType: stable
      - job: validate_docker
        steps:
          - task: CmdLine@2
            inputs:
              script: |
                echo $GIT_COMMIT
                echo $GIT_BRANCH
                




