apiVersion: batch/v1
kind: CronJob
metadata:
  name: echo-smthing
  namespace: devops
spec:
  schedule: "0 23 * * 6"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: echo-smthing
            image: busybox
            args: ['/bin/sh', '-c', 'date; echo Hello from the Kubernetes cluster']
          restartPolicy: "OnFailure"