# general parameters
namespace: devops
# deployment parameters
replicasCount: 1
image:
  name: app3
  repository: devopsorient.azurecr.io/webpage8003
  tag: latest
  containerPort: 80
resources:
  memory: "256Mi"
  cpu: "0.1"
env:
  valueMessage: "App 3 "
  valuePort: "80"
  secret: mysecret
# service parameters
service:
  protocol: TCP
  portExpose: 80
  portTarget: 80
  
serviceAccountName: service-account-1